version: '2'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - docker.env
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\""]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
