export enum PaymentErrorCode {
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
    SESSION_ALREADY_OPEN = 'SESSION_ALREADY_OPEN',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
}
